using Microsoft.SemanticKernel;
using System.ComponentModel;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Text.Json;
using System.Threading.Tasks;

namespace playwright.test.generator.Plugins
{
    
    public class PlaywrightTestScriptPlugin
    {

        public const string KernelFunctionName="evaluate_playwright_test_script";

        [KernelFunction(KernelFunctionName)]
        [Description("Returns the output of the provided playwright test script generated by the assistant. Assistant MUST call this function only after all scenario steps have been executed. If the script runs without errors and all test pass, assistant must reply with these exact words 'TEST OK'. If the script has still errors after the assistant has tried to fox it up to the maximum amount of time, , assistant must reply with these exact words 'TEST KO'")]
        public string EvaluatePlaywrightTestScript(
            [Description("the assistant generated playwright test script")] string playWrightScript)
        {
            //TODO : call
            // save the script to a file and run it and get result from stdout 
            //npx playwright test playwright/playwright-auto-generated-tests/test-6e2b1c7a-2c3d-4e7a-9b1c-7a2c3d4e7a9b.spec.ts
            //return the output of the script execution
            throw new NotImplementedException("This function is not implemented yet. Please implement the logic to execute the Playwright test script and return the result."); 
        }
    }
   
}
